//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenStockApp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenStockApp.Resources.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use this page to browse your saved alert options. Select a product (only products that have been enabled by using &quot;Add Notifications&quot; will be shown). Then browse all your active notifications. 
        ///You can make changes to them and save them by clicking the button at the bottom of the page.
        ///If you do not see any active alerts in here, make sure you have clicked &quot;Save Alert Settings&quot; when adding the alerts..
        /// </summary>
        public static string ActiveNotificationsExplanation {
            get {
                return ResourceManager.GetString("ActiveNotificationsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use this page?.
        /// </summary>
        public static string ActiveNotificationsExplanationTitle {
            get {
                return ResourceManager.GetString("ActiveNotificationsExplanationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to customize your alerts you must set your alerts here. The retailer options allow you to choose which retailers you want to be notified about. You can choose retailers from multiple countries. The product options allow you to select which products (RTX 3080, etc) you want to be notified about. In order to browse the available products, you must first choose a product, and then a list of available models (AIBs) will appear. You may search on the list. Or scroll down. Finally click &quot;Save Alert Setti [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AddNotificationsExplanation {
            get {
                return ResourceManager.GetString("AddNotificationsExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use this page?.
        /// </summary>
        public static string AddNotificationsExplanationTitle {
            get {
                return ResourceManager.GetString("AddNotificationsExplanationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Your Font Size Scaling (%).
        /// </summary>
        public static string AdvancedSettingsFontSizeText {
            get {
                return ResourceManager.GetString("AdvancedSettingsFontSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size Scaling.
        /// </summary>
        public static string AdvancedSettingsPageFontSizeTitle {
            get {
                return ResourceManager.GetString("AdvancedSettingsPageFontSizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the checkbox to enable software only rendering, reducing your GPU usage. You must restart the app for this to take effect..
        /// </summary>
        public static string AdvancedSettingsPageRenderCheckBox {
            get {
                return ResourceManager.GetString("AdvancedSettingsPageRenderCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Software Rendering (disabled by default).
        /// </summary>
        public static string AdvancedSettingsPageRenderText {
            get {
                return ResourceManager.GetString("AdvancedSettingsPageRenderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering Mode.
        /// </summary>
        public static string AdvancedSettingsPageRenderTitle {
            get {
                return ResourceManager.GetString("AdvancedSettingsPageRenderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockDrops.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Add to Cart Url.
        /// </summary>
        public static string AtcUrlButtonText {
            get {
                return ResourceManager.GetString("AtcUrlButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentGrid.
        /// </summary>
        public static string ContentGridPageTitle {
            get {
                return ResourceManager.GetString("ContentGridPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login attempt timed out. Please try again. You need to be logged in to use the app..
        /// </summary>
        public static string DialogAuthenticationTimedOutContent {
            get {
                return ResourceManager.GetString("DialogAuthenticationTimedOutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Timed Out.
        /// </summary>
        public static string DialogAuthenticationTimedOutTitle {
            get {
                return ResourceManager.GetString("DialogAuthenticationTimedOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Authentication.
        /// </summary>
        public static string DialogAuthenticationTitle {
            get {
                return ResourceManager.GetString("DialogAuthenticationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no internet connection, please connect to the internet and try again..
        /// </summary>
        public static string DialogNoNetworkAvailableContent {
            get {
                return ResourceManager.GetString("DialogNoNetworkAvailableContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong during the login, please try again..
        /// </summary>
        public static string DialogStatusUnknownErrorContent {
            get {
                return ResourceManager.GetString("DialogStatusUnknownErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Nothing (except sending a ping).
        /// </summary>
        public static string DoNothingActionText {
            get {
                return ResourceManager.GetString("DoNothingActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Alert Settings.
        /// </summary>
        public static string FilterAlertsSwitchText {
            get {
                return ResourceManager.GetString("FilterAlertsSwitchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the add to cart url automatically when available.
        /// </summary>
        public static string OpenAddToCartUrl {
            get {
                return ResourceManager.GetString("OpenAddToCartUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the product url for notifications automatically.
        /// </summary>
        public static string OpenProductUrl {
            get {
                return ResourceManager.GetString("OpenProductUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Product Url.
        /// </summary>
        public static string ProductUrlButtonText {
            get {
                return ResourceManager.GetString("ProductUrlButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string SettingsAboutPageTitle {
            get {
                return ResourceManager.GetString("SettingsAboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Portal.
        /// </summary>
        public static string SettingsAboutUserPortalLinkText {
            get {
                return ResourceManager.GetString("SettingsAboutUserPortalLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name Here.
        /// </summary>
        public static string SettingsDefaultUsername {
            get {
                return ResourceManager.GetString("SettingsDefaultUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Settings.
        /// </summary>
        public static string SettingsIntegrationsEmailTitle {
            get {
                return ResourceManager.GetString("SettingsIntegrationsEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrations.
        /// </summary>
        public static string SettingsIntegrationsTitle {
            get {
                return ResourceManager.GetString("SettingsIntegrationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockDrops App. Copyright StockDrops, {0}..
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this application.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Your Theme.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Discord webhook URL to send a message to your server..
        /// </summary>
        public static string SettingsPageDiscordText {
            get {
                return ResourceManager.GetString("SettingsPageDiscordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Integration (gold users only).
        /// </summary>
        public static string SettingsPageDiscordTitle {
            get {
                return ResourceManager.GetString("SettingsPageDiscordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Not Disturb.
        /// </summary>
        public static string SettingsPageDoNotDisturbText {
            get {
                return ResourceManager.GetString("SettingsPageDoNotDisturbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your SMTP Email settings to send an email every  time you receive a notification. Or log in into your email provider..
        /// </summary>
        public static string SettingsPageEmailText {
            get {
                return ResourceManager.GetString("SettingsPageEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Settings.
        /// </summary>
        public static string SettingsPageEmailTitle {
            get {
                return ResourceManager.GetString("SettingsPageEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Agreement.
        /// </summary>
        public static string SettingsPageLicenseAgreementText {
            get {
                return ResourceManager.GetString("SettingsPageLicenseAgreementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string SettingsPageLogInButtonText {
            get {
                return ResourceManager.GetString("SettingsPageLogInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string SettingsPageLogOutButtonText {
            get {
                return ResourceManager.GetString("SettingsPageLogOutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable this to minimize to tray.
        /// </summary>
        public static string SettingsPageMinimizeToTrayCheckBox {
            get {
                return ResourceManager.GetString("SettingsPageMinimizeToTrayCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to Tray.
        /// </summary>
        public static string SettingsPageMinimizeToTrayText {
            get {
                return ResourceManager.GetString("SettingsPageMinimizeToTrayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize Behavior.
        /// </summary>
        public static string SettingsPageMinimizeToTrayTitle {
            get {
                return ResourceManager.GetString("SettingsPageMinimizeToTrayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user logged in, please click &quot;Log In&quot; to log in..
        /// </summary>
        public static string SettingsPageNoUserLoggedInText {
            get {
                return ResourceManager.GetString("SettingsPageNoUserLoggedInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string SettingsPageRadioButtonDNDOff {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDNDOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string SettingsPageRadioButtonDNDOn {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDNDOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Open Websites Without Alerts.
        /// </summary>
        public static string SettingsPageRadioButtonDNDWebsites {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDNDWebsites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        public static string SettingsPageStartupCheckBox {
            get {
                return ResourceManager.GetString("SettingsPageStartupCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define your startup preferences.
        /// </summary>
        public static string SettingsPageStartupText {
            get {
                return ResourceManager.GetString("SettingsPageStartupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        public static string SettingsPageStartupTitle {
            get {
                return ResourceManager.GetString("SettingsPageStartupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string SettingsPageUserTitle {
            get {
                return ResourceManager.GetString("SettingsPageUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test your webhook.
        /// </summary>
        public static string SettingsTestWebhookButtonText {
            get {
                return ResourceManager.GetString("SettingsTestWebhookButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        public static string SettingsUpdateButtonText {
            get {
                return ResourceManager.GetString("SettingsUpdateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh User.
        /// </summary>
        public static string SettingsUserRefreshButton {
            get {
                return ResourceManager.GetString("SettingsUserRefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing User....
        /// </summary>
        public static string SettingsUserRefreshing {
            get {
                return ResourceManager.GetString("SettingsUserRefreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshed User. Button in timeout....
        /// </summary>
        public static string SettingsUserRefreshingInTimeout {
            get {
                return ResourceManager.GetString("SettingsUserRefreshingInTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhook URL.
        /// </summary>
        public static string SettingsWebhookUrl {
            get {
                return ResourceManager.GetString("SettingsWebhookUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Webhook.
        /// </summary>
        public static string SettingsWebhookUrlButtonText {
            get {
                return ResourceManager.GetString("SettingsWebhookUrlButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Shell_LogIn {
            get {
                return ResourceManager.GetString("Shell_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Notifications.
        /// </summary>
        public static string ShellActiveNotifications {
            get {
                return ResourceManager.GetString("ShellActiveNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Notifications.
        /// </summary>
        public static string ShellAddNotifications {
            get {
                return ResourceManager.GetString("ShellAddNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Settings.
        /// </summary>
        public static string ShellAlertSettings {
            get {
                return ResourceManager.GetString("ShellAlertSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentGrid.
        /// </summary>
        public static string ShellContentGridPage {
            get {
                return ResourceManager.GetString("ShellContentGridPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or close navigation.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
    }
}
